# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(through='cartapp.LineItem', to='cartapp.Order'),
        ),
    ]
